name: Test
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: test code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: test
        run: make test
