name: Test Code
on: 
  push:
    branches:
      - main

jobs:
  host_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Test
      run: make test
  
  docker_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test Docker file
      run: docker build -t mpm:0.0.1 .

